### ISSUE TITLE
关于bkssm服务能开源吗？什么时候？关于access_token 逻辑什么时候完全合并至bkauth？

### ISSUE THREAD

**Issue by Laotanling** [TencentBlueKing/blueking-auth#37]
please add issue here: https://github.com/TencentBlueKing/blueking-auth/issues

**Comment by wklken** [comment]
bkssm 不会开源，后续access_token 逻辑会由bkauth 承载，然后下掉 bkssm 模块；

暂定规划放在 2025 上半年
